refactor: move to RxJava3
gravitee-io/gravitee-cockpit-connectors pull request #171
Opened 2022-09-26 15:00 UTC by jgiovaresco

**Issue**

https://graviteedevops.atlassian.net/browse/COC-49

**Description**

BREAKING CHANGE: rxJava3 required

2022-09-28 09:22 UTC, loriepisicchio approved these changes

2022-10-19 14:18 UTC, marcambier commented on pom.xml
> +        <gravitee-node.version>2.0.0-bumpRxJava3-SNAPSHOT</gravitee-node.version>
Could you please set it to the pre-released version ?
```suggestion
        <gravitee-node.version>2.0.0-alpha.3</gravitee-node.version>
```

2022-10-19 14:19 UTC, marcambier commented on pom.xml
> +        <gravitee-cockpit-api.version>2.0.0-bumpRxJava-SNAPSHOT</gravitee-cockpit-api.version>
Could you please set it to the pre-released version ?
```suggestion
        <gravitee-cockpit-api.version>2.0.0-alpha.1</gravitee-cockpit-api.version>
```

2022-10-19 14:21 UTC, marcambier requested changes
Hello !
We made some pre-release versions of gravitee-node and cockpit-api.
So we would better use them than snapshots

2022-10-19 14:24 UTC, marcambier approved these changes

2022-10-20 07:53 UTC, merged

2022-10-20 07:55 UTC, graviteeio commented
:tada: This PR is included in version 3.0.0-alpha.1 :tada:

The release is available on:
- `3.0.0-alpha.1`
- [GitHub release](https://github.com/gravitee-io/gravitee-cockpit-connectors/releases/tag/3.0.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-12-12 14:27 UTC, graviteeio commented
:tada: This PR is included in version 3.0.0 :tada:

The release is available on:
- `3.0.0`
- [GitHub release](https://github.com/gravitee-io/gravitee-cockpit-connectors/releases/tag/3.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: